Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -19,18 +18,13 @@ jobs:
         USER: ${{ secrets.AWS_VM_USERNAME }}
       run: |
         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-        # Create a temporary directory on EC2 instance
-        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'mkdir -p ~/app_ohif_tmp'  
-
-        # Copy files to the EC2 instance
+        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'mkdir -p ~/app_ohif_tmp'
         scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:~/app_ohif_tmp
-        
-        # Move the new build to the web root and clean up
         ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
-          sudo rm -rf /var/www/html/ohif-viewer/app
-          sudo mv ~/app_ohif_tmp/* /var/www/html/ohif-viewer/app
-          rm -rf ~/app_ohif_tmp 
+          sudo rm -rf /var/www/html/ohif-viewer/app/*
+          sudo mv ~/app_ohif_tmp /var/www/html/ohif-viewer/app
         '
+
     - name: Build and run Docker container on EC2
       env:
         PRIVATE_KEY: ${{ secrets.AWS_VM_SSH_KEY }}
@@ -39,22 +33,28 @@ jobs:
       run: |
         ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
           cd /var/www/html/ohif-viewer/app
-          docker build -t ohif-viewer-image .
-
-          # Check if the container exists and stop it if running
+          
+          if [ ! -f Dockerfile ]; then
+            echo "Dockerfile not found in expected location!"
+            exit 1
+          fi
+          
+          IMAGE_TAG=$(date +%s)
+          docker build -t ohif-viewer-image:$IMAGE_TAG .
+          
           if [ $(docker ps -q -f name=ohif-viewer-container) ]; then
             echo "Stopping existing container..."
             docker stop ohif-viewer-container
           fi
-
-          # Check if the container exists and remove it (along with associated volumes)
+          
           if [ $(docker ps -a -q -f name=ohif-viewer-container) ]; then
             echo "Removing existing container and its volumes..."
             docker rm -v ohif-viewer-container
           fi
-
-          # Run the new container, mapping necessary volumes and ports
-          docker run -d -p 3000:80/tcp -v /var/www/html/ohif-viewer/default.js:/usr/share/nginx/html/app-config.js --name ohif-viewer-container ohif-viewer-image
+          
+          docker run -d -p 3000:80/tcp \
+            -v /var/www/html/ohif-viewer/default.js:/usr/share/nginx/html/app-config.js \
+            --name ohif-viewer-container ohif-viewer-image:$IMAGE_TAG
         '
 
     - name: Cleanup
